services:
  - type: web
    name: pigeon-racing
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
